### ISSUE TITLE
Fuzzing corpus including null bytes not parsed properly

### ISSUE THREAD

**Issue by sgIOlas** [AFLplusplus/unicornafl#13]
After discussing about this on Qiling's telegram user group, this seemed to be a bug indeed so this is the corresponding bug report.

## Description
The code that handles input parsing for AFL++ does not seem to be properly parsing the files included in the fuzzing corpus when these include null bytes that are not placed at the end of the file. As a result, if an input file contains "**\xAA\xBB\x00\xCC\xDD**", `_place_input_cb` will internally use "**\xAA\xBB\x00\x00\x00**" as input bytes.

## Expected behavior
The input bytes used to call `_place_input_cb` are the same as the ones present in the input file.

## Steps to reproduce
The referenced source code is available at this [repo](https://github.com/Olasergiolas/TFG/tree/issue-unicornafl-parsing/Fuzzing/Qiling/netgear).

 Content of "input":
![image](https://user-images.githubusercontent.com/32015541/171235097-9b4ba52e-74c0-407a-8f3a-ba351408ae76.png)

1. Run the fuzzing python script: `python src/dev/fuzz.py input`
2. Verify that only the bytes before the first \x00 were used as input and written to memory.
![image](https://user-images.githubusercontent.com/32015541/171235457-1ec02e15-3fe5-4b7e-b47f-4328f7e210b1.png)

## Versions used
Latest unicornafl from source.
![image](https://user-images.githubusercontent.com/32015541/171234066-de4666b0-667c-49a4-9300-250a7469c4ad.png)

**Comment by wtdcode** [comment]
Hello, thanks for your issue and a fix is on the way.

**Comment by wtdcode** [comment]
Close due to #15 fixed.
