### ISSUE TITLE
Why "& (MAP_SIZE - 7)" instead of "& (MAP_SIZE - 1)" when calculating coverage? [unicornafl.cpp#L332]

### ISSUE THREAD

**Issue by shandianchengzi** [AFLplusplus/unicornafl#20]
Hi,

In [qemuafl#L126](https://github.com/AFLplusplus/qemuafl/blob/master/accel/tcg/translate-all.c#L126), [fuzzware-unicorn](https://github.com/fuzzware-fuzzer/unicorn/blob/8cb665bf67b1f8fa04cc916b25d20732d1fbcc81/qemu/translate-all.c#L177), [AFL#L251](https://github.com/google/AFL/blob/HEAD/qemu_mode/patches/afl-qemu-cpu-inl.h#L251) and [AFLplusplus#119](https://github.com/AFLplusplus/AFLplusplus/blob/HEAD/utils/qbdi_mode/template.cpp#L119), it is `& (MAP_SIZE - 1)`.
But in [unicornafl.cpp#L332](https://github.com/AFLplusplus/unicornafl/blob/main/unicornafl.cpp#L335), I see `& (MAP_SIZE - 7)`. 

Is this a necessary special modification?

**Comment by wtdcode** [comment]
Good question. I forget where I got this when I wrote this but I exactly held the same question at that moment. Considering the reference you gave, I believe it's a bug.

**Comment by shandianchengzi** [comment]
Thanks for reply.

In my test, it has no obvious impact on code execution. 
So will you change it to 1 in later versions?

**Comment by shandianchengzi** [comment]
> Good question. I forget where I got this when I wrote this but I exactly held the same question at that moment. Considering the reference you gave, I believe it's a bug.

I found where you got this! When I check the branch uc1, I found `MAP_SIZE - 7` in [https://github.com/AFLplusplus/unicornafl/blob/uc1/afl-unicorn-cpu-translate-inl.h#L46](https://github.com/AFLplusplus/unicornafl/blob/uc1/afl-unicorn-cpu-translate-inl.h#L46).

Now it confused me. Maybe I need to check the commit log to know more about that.

**Comment by vanhauser-thc** [comment]
The -7 is wrong, it should be -1.
But please note that also the "hashing" of the address performed the line above is outdated, I should have fixed that or told someone that there is a better solution.
`cur_loc = (cur_loc >> 4) ^ (cur_loc << 8);` this produces too many collisions.

Please use this instead:
https://github.com/AFLplusplus/qemuafl/blob/master/qemuafl/imported/afl_hash.h
uint32_t afl_hash_ip(uint64_t ip);

or use xxhash directly as this is just a port because qemu has a version that collides.

Edit: you still have to do `&= (MAP_SIZE - 1)` after calling this function or xxhash3

**Comment by wtdcode** [comment]
> The -7 is wrong, it should be -1. But please note that also the "hashing" of the address performed the line above is outdated, I should have fixed that or told someone that there is a better solution. `cur_loc = (cur_loc >> 4) ^ (cur_loc << 8);` this produces too many collisions.
> 
> Please use this instead: https://github.com/AFLplusplus/qemuafl/blob/master/qemuafl/imported/afl_hash.h uint32_t afl_hash_ip(uint64_t ip);
> 
> or use xxhash directly as this is just a port because qemu has a version that collides.
> 
> Edit: you still have to do `&= (MAP_SIZE - 1)` after calling this function or xxhash3

Nice hint. Will fix it.

**Comment by shandianchengzi** [comment]
> The -7 is wrong, it should be -1. But please note that also the "hashing" of the address performed the line above is outdated, I should have fixed that or told someone that there is a better solution. `cur_loc = (cur_loc >> 4) ^ (cur_loc << 8);` this produces too many collisions.
> 
> Please use this instead: https://github.com/AFLplusplus/qemuafl/blob/master/qemuafl/imported/afl_hash.h uint32_t afl_hash_ip(uint64_t ip);
> 
> or use xxhash directly as this is just a port because qemu has a version that collides.
> 
> Edit: you still have to do `&= (MAP_SIZE - 1)` after calling this function or xxhash3

Got it. Hope this feature can also be synchronized on the uc1 branch.  : )

**Comment by wtdcode** [comment]
> > The -7 is wrong, it should be -1. But please note that also the "hashing" of the address performed the line above is outdated, I should have fixed that or told someone that there is a better solution. `cur_loc = (cur_loc >> 4) ^ (cur_loc << 8);` this produces too many collisions.
> > Please use this instead: https://github.com/AFLplusplus/qemuafl/blob/master/qemuafl/imported/afl_hash.h uint32_t afl_hash_ip(uint64_t ip);
> > or use xxhash directly as this is just a port because qemu has a version that collides.
> > Edit: you still have to do `&= (MAP_SIZE - 1)` after calling this function or xxhash3
> 
> Got it. Hope this feature can also be synchronized on the uc1 branch. : )

Any reason you stick to uc1?

**Comment by shandianchengzi** [comment]
> > Got it. Hope this feature can also be synchronized on the uc1 branch. : )
> 
> Any reason you stick to uc1?

Good question!!!

I don't know how to analyze the overhead of hook in unicornafl2, 
and there are many repositories developed based on afl-unicorn(no hook).
to compare, I have to turn back to uc1.

Maybe I will open another issue to clearly describe my confusion on the overhead.

**Comment by wtdcode** [comment]
> > > > The -7 is wrong, it should be -1. But please note that also the "hashing" of the address performed the line above is outdated, I should have fixed that or told someone that there is a better solution. `cur_loc = (cur_loc >> 4) ^ (cur_loc << 8);` this produces too many collisions.
> > > > Please use this instead: https://github.com/AFLplusplus/qemuafl/blob/master/qemuafl/imported/afl_hash.h uint32_t afl_hash_ip(uint64_t ip);
> > > > or use xxhash directly as this is just a port because qemu has a version that collides.
> > > > Edit: you still have to do `&= (MAP_SIZE - 1)` after calling this function or xxhash3
> > > 
> > > 
> > > Got it. Hope this feature can also be synchronized on the uc1 branch. : )
> > 
> > 
> > Any reason you stick to uc1?
> 
> Good question!!!
> 
> I don't know how to analyze the overhead of hook in unicornafl2, and there are many repositories developed based on afl-unicorn(no hook). to compare, I have to turn back to uc1.
> 
> Maybe I will open another issue to clearly describe my confusion on the overhead.

The overhead is exactly the same as the inline hook has been implemented in the official Unicorn2 repository. Meanwhile , you will get at most 20% performance boost by simply switching to uc2.

**Comment by shandianchengzi** [comment]
> The overhead is exactly the same as the inline hook has been implemented in the official Unicorn2 repository. Meanwhile , you will get at most 20% performance boost by simply switching to uc2.

Many papers, such as January 2023 [ICICLE: A Re-Designed Emulator for Grey-Box Firmware Fuzzing](https://www.researchgate.net/publication/367652433_ICICLE_A_Re-Designed_Emulator_for_Grey-Box_Firmware_Fuzzing), note hooking API imposes additional overheads.

![image](https://user-images.githubusercontent.com/58585665/224557685-edb2e40b-c288-4fe0-8fd0-714148d3e46c.png)

When comparing, 
it is **hard to explain** whether the additional overheads of hook can be offset by the improvement of uc2,
or which part to reduce the overhead of hook.

**Comment by wtdcode** [comment]
1. The claim is wrong as obviously, we are using Hook API.
2. The block hooking API imposes additional overheads but doesn't account too much. The most significant overhead is soft mmu emulation.

**Comment by shandianchengzi** [comment]
>> Got it. Hope this feature can also be synchronized on the uc1 branch. : )
> 1. The claim is wrong as obviously, we are using Hook API.
> 2. The block hooking API imposes additional overheads but doesn't account too much. The most significant overhead is soft mmu emulation.

1. This paper uses AFLplusplus 4.01a. The 4.01c was released on Jan 28, and use of Hook API started on Jan 20. So its claim is reasonable.
2. I also agree with that. In my test, the performance of uc2 is indeed better than that of uc1. I will consider returning to uc2 after the theoretical comparison.

Edit: Undo my hope~

**Comment by wtdcode** [comment]
Fixed and used the new hash algo from qemuafl.
