### ISSUE TITLE
cur_loc overflow in _uc_hook_block

### ISSUE THREAD

**Issue by futhewo** [AFLplusplus/unicornafl#21]
Hello,

Commit 979d944 replaced:
`uint64_t cur_loc = ((address >> 4) ^ (address << 8)) & (MAP_SIZE - 7);`

With:
`uint64_t cur_loc = afl_hash_ip(address);`

It is later used as:
`ucafl->afl_area_ptr_[cur_loc ^ ucafl->afl_prev_loc_]++;`

After the commit, cur_loc is not always in ucafl->afl_area_ptr_ range, hence leading to a segfault (at least in my tests).

A simple patch may be:
`uint64_t cur_loc = afl_hash_ip(address) & (MAP_SIZE - 7);`

Or, as in qemuafl:
`uint64_t cur_loc = afl_hash_ip(address) & (MAP_SIZE - 1);`

I don't know which is best and maybe I am mistaken.
Have a nice day.

**Comment by wtdcode** [comment]
It’s my error. Thanks for report.

The second should be correct at first glance.

**Comment by futhewo** [comment]
Thanks for the quick answer.
