### ISSUE TITLE
Unicorn mode doesn't seem to work!

### ISSUE THREAD

**Issue by keesj-exset** [AFLplusplus/unicornafl#6]
Helo,

I am trying to get ALF Unicorn nicely working. I am currently building it from source and in the recent weeks, my build stopped working   

I am currently getting the following error:
Finished processing dependencies for unicornafl==2.0.1
[*] If needed, you can (re)install the bindings from `./unicornafl/bindings/python` using `python setup.py install`
[*] Unicornafl bindings installed successfully.
[*] Testing unicornafl python functionality by running a sample test harness
Showmap
[-] Error: Unicorn mode doesn't seem to work!

I am using the attached script to build
[build_afl.txt](https://github.com/AFLplusplus/unicornafl/files/8196215/build_afl.txt)

As you might  notice also I am trying to install the package globally hence the last command
sudo python3 setup.py install --force --prefix=/usr/local (as the script either assumes 

any help is appreciated

**Comment by 0xDEADC0DE55** [comment]
https://github.com/AFLplusplus/AFLplusplus/blob/1d4f1e48797c064ee71441ba555b29fc3f467983/unicorn_mode/build_unicorn_support.sh#L220

The command in `unicorn_mode/build_unicorn_support.sh` for AFL++ is missing argument `-i sample_inputs/` for `afl-showmap`.

**Comment by keesj-exset** [comment]
I will give it a try and send a patch it this is all

**Comment by keesj-exset** [comment]
Hi, it looks like more is going on and I can not run a hello world without causing a segfault

**Comment by keesj-exset** [comment]
While I created a patch I had to test on the development branch of the project and the issue is not present there. hence .. closing this issue
