### ISSUE TITLE
The testcase placement code doesn't work with NUL characters

### ISSUE THREAD

**Issue by justdionysus** [AFLplusplus/unicornafl#7]
The `ctypes`-based callbacks (for place input and validate crash) shouldn't be using `c_char_p` for the input buffer. `c_char_p` expects a NUL terminated C-string and will auto convert to a `bytes` object.

**Comment by ghost** [comment]
I have meet the same trouble, and solve it temporarily by changing `c_char_p` to `c_void_p`.

**Comment by domenukk** [comment]
Should be fixed with #15
