### ISSUE TITLE
Working Example 

### ISSUE THREAD

**Issue by MFaisalZaki** [AFLplusplus/unicornafl#8]
Can you provide the same example found in [afl-unicorn](https://github.com/Battelle/afl-unicorn/tree/master/unicorn_mode/samples/simple) since I cannot get it to run?

**Comment by wtdcode** [comment]
Hello, sorry for the late reply. How to reproduce?

**Comment by domenukk** [comment]
The updated examples are here 
https://github.com/AFLplusplus/AFLplusplus/tree/stable/unicorn_mode/samples
